# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 650)
        MainWindow.setMinimumSize(QtCore.QSize(900, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background:rgb(91,90,90);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toodle = QtWidgets.QFrame(self.frame_top)
        self.frame_toodle.setMinimumSize(QtCore.QSize(80, 25))
        self.frame_toodle.setMaximumSize(QtCore.QSize(80, 25))
        self.frame_toodle.setStyleSheet("background: rgb(51,51,51);")
        self.frame_toodle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toodle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_toodle.setObjectName("frame_toodle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_toodle)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout.addWidget(self.frame_toodle)
        self.frame_top_east = QtWidgets.QFrame(self.frame_top)
        self.frame_top_east.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_top_east.setStyleSheet("background:rgb(51,51,51);")
        self.frame_top_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_east.setObjectName("frame_top_east")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_east)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_appname = QtWidgets.QFrame(self.frame_top_east)
        self.frame_appname.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_appname.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_appname.setObjectName("frame_appname")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_appname)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lab_appname = QtWidgets.QLabel(self.frame_appname)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_appname.sizePolicy().hasHeightForWidth())
        self.lab_appname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(14)
        self.lab_appname.setFont(font)
        self.lab_appname.setStyleSheet("color:rgb(255,255,255);")
        self.lab_appname.setObjectName("lab_appname")
        self.horizontalLayout_10.addWidget(self.lab_appname)
        self.horizontalLayout_4.addWidget(self.frame_appname)
        self.frame_min = QtWidgets.QFrame(self.frame_top_east)
        self.frame_min.setMinimumSize(QtCore.QSize(30, 25))
        self.frame_min.setMaximumSize(QtCore.QSize(30, 25))
        self.frame_min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_min.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_min.setObjectName("frame_min")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_min)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bn_min = QtWidgets.QPushButton(self.frame_min)
        self.bn_min.setMinimumSize(QtCore.QSize(30, 25))
        self.bn_min.setMaximumSize(QtCore.QSize(30, 25))
        self.bn_min.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/1x/hideAsset 53.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_min.setIcon(icon)
        self.bn_min.setIconSize(QtCore.QSize(22, 22))
        self.bn_min.setFlat(True)
        self.bn_min.setObjectName("bn_min")
        self.horizontalLayout_7.addWidget(self.bn_min)
        self.horizontalLayout_4.addWidget(self.frame_min)
        self.frame_max = QtWidgets.QFrame(self.frame_top_east)
        self.frame_max.setMinimumSize(QtCore.QSize(30, 25))
        self.frame_max.setMaximumSize(QtCore.QSize(30, 25))
        self.frame_max.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_max.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_max.setObjectName("frame_max")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_max)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bn_max = QtWidgets.QPushButton(self.frame_max)
        self.bn_max.setMinimumSize(QtCore.QSize(30, 25))
        self.bn_max.setMaximumSize(QtCore.QSize(30, 25))
        self.bn_max.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_max.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/1x/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_max.setIcon(icon1)
        self.bn_max.setIconSize(QtCore.QSize(22, 22))
        self.bn_max.setFlat(True)
        self.bn_max.setObjectName("bn_max")
        self.horizontalLayout_6.addWidget(self.bn_max)
        self.horizontalLayout_4.addWidget(self.frame_max)
        self.frame_close = QtWidgets.QFrame(self.frame_top_east)
        self.frame_close.setMinimumSize(QtCore.QSize(30, 25))
        self.frame_close.setMaximumSize(QtCore.QSize(30, 25))
        self.frame_close.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bn_close = QtWidgets.QPushButton(self.frame_close)
        self.bn_close.setMinimumSize(QtCore.QSize(30, 0))
        self.bn_close.setMaximumSize(QtCore.QSize(30, 25))
        self.bn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close.setIcon(icon2)
        self.bn_close.setIconSize(QtCore.QSize(22, 22))
        self.bn_close.setFlat(True)
        self.bn_close.setObjectName("bn_close")
        self.horizontalLayout_5.addWidget(self.bn_close)
        self.horizontalLayout_4.addWidget(self.frame_close)
        self.horizontalLayout.addWidget(self.frame_top_east)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_bottom_west = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_west.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_bottom_west.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_bottom_west.setStyleSheet("background:rgb(51,51,51);")
        self.frame_bottom_west.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_west.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_west.setObjectName("frame_bottom_west")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom_west)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_home = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_home.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_home.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_home.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_home.setObjectName("frame_home")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_home)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bn_cargolist = QtWidgets.QPushButton(self.frame_home)
        self.bn_cargolist.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_cargolist.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_cargolist.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(0,178,178);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_cargolist.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/1x/homeAsset 46.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_cargolist.setIcon(icon3)
        self.bn_cargolist.setIconSize(QtCore.QSize(22, 22))
        self.bn_cargolist.setFlat(True)
        self.bn_cargolist.setObjectName("bn_cargolist")
        self.horizontalLayout_15.addWidget(self.bn_cargolist)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame_home)
        self.frame_bug = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_bug.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_bug.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_bug.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bug.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bug.setObjectName("frame_bug")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_bug)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bn_cargopage = QtWidgets.QPushButton(self.frame_bug)
        self.bn_cargopage.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_cargopage.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_cargopage.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,178,178);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_cargopage.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/1x/bugAsset 47.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_cargopage.setIcon(icon4)
        self.bn_cargopage.setIconSize(QtCore.QSize(22, 22))
        self.bn_cargopage.setFlat(True)
        self.bn_cargopage.setObjectName("bn_cargopage")
        self.horizontalLayout_16.addWidget(self.bn_cargopage)
        self.verticalLayout_3.addWidget(self.frame_bug)
        self.frame_cloud = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_cloud.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_cloud.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_cloud.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_cloud.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_cloud.setObjectName("frame_cloud")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_cloud)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_3.addWidget(self.frame_cloud)
        self.frame_android = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_android.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_android.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_android.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android.setObjectName("frame_android")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_android)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_3.addWidget(self.frame_android)
        self.frame_8 = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_bottom_west)
        self.frame_bottom_east = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_east.setObjectName("frame_bottom_east")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_bottom_east)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 55))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setStyleSheet("background:rgb(91,90,90);")
        self.page_home.setObjectName("page_home")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.page_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.lab_bug_title = QtWidgets.QLabel(self.frame_7)
        self.lab_bug_title.setGeometry(QtCore.QRect(25, 0, 810, 55))
        self.lab_bug_title.setMinimumSize(QtCore.QSize(0, 55))
        self.lab_bug_title.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.lab_bug_title.setFont(font)
        self.lab_bug_title.setStyleSheet("color:rgb(255,255,255);")
        self.lab_bug_title.setObjectName("lab_bug_title")
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.page_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.cargolist_table_widget = QtWidgets.QTableWidget(self.frame_9)
        self.cargolist_table_widget.setStyleSheet("QTableWidget {\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #cccccc;\n"
"    background-color: rgb(51, 51, 51);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.cargolist_table_widget.setObjectName("cargolist_table_widget")
        self.cargolist_table_widget.setColumnCount(5)
        self.cargolist_table_widget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.cargolist_table_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargolist_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargolist_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargolist_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargolist_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargolist_table_widget.setHorizontalHeaderItem(4, item)
        self.cargolist_table_widget.horizontalHeader().setMinimumSectionSize(100)
        self.horizontalLayout_30.addWidget(self.cargolist_table_widget)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_home)
        self.page_bug = QtWidgets.QWidget()
        self.page_bug.setStyleSheet("background:rgb(91,90,90);")
        self.page_bug.setObjectName("page_bug")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.page_bug)
        self.horizontalLayout_19.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_home_main = QtWidgets.QFrame(self.page_bug)
        self.frame_home_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home_main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_home_main.setObjectName("frame_home_main")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_home_main)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_home_main)
        self.frame_5.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_home_main_title = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_home_main_title.sizePolicy().hasHeightForWidth())
        self.label_home_main_title.setSizePolicy(sizePolicy)
        self.label_home_main_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_home_main_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(20)
        self.label_home_main_title.setFont(font)
        self.label_home_main_title.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.label_home_main_title.setTextFormat(QtCore.Qt.RichText)
        self.label_home_main_title.setObjectName("label_home_main_title")
        self.horizontalLayout_9.addWidget(self.label_home_main_title)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.line_cargopage_current = QtWidgets.QLineEdit(self.frame_5)
        self.line_cargopage_current.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_cargopage_current.sizePolicy().hasHeightForWidth())
        self.line_cargopage_current.setSizePolicy(sizePolicy)
        self.line_cargopage_current.setMinimumSize(QtCore.QSize(50, 25))
        self.line_cargopage_current.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_cargopage_current.setFont(font)
        self.line_cargopage_current.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"    margin-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_cargopage_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_cargopage_current.setObjectName("line_cargopage_current")
        self.horizontalLayout_9.addWidget(self.line_cargopage_current)
        self.label_home_main_slash = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_home_main_slash.sizePolicy().hasHeightForWidth())
        self.label_home_main_slash.setSizePolicy(sizePolicy)
        self.label_home_main_slash.setMinimumSize(QtCore.QSize(0, 0))
        self.label_home_main_slash.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.label_home_main_slash.setFont(font)
        self.label_home_main_slash.setStyleSheet("")
        self.label_home_main_slash.setTextFormat(QtCore.Qt.RichText)
        self.label_home_main_slash.setObjectName("label_home_main_slash")
        self.horizontalLayout_9.addWidget(self.label_home_main_slash)
        self.line_cargopage_total = QtWidgets.QLineEdit(self.frame_5)
        self.line_cargopage_total.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_cargopage_total.sizePolicy().hasHeightForWidth())
        self.line_cargopage_total.setSizePolicy(sizePolicy)
        self.line_cargopage_total.setMinimumSize(QtCore.QSize(50, 25))
        self.line_cargopage_total.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_cargopage_total.setFont(font)
        self.line_cargopage_total.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"    margin-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_cargopage_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_cargopage_total.setObjectName("line_cargopage_total")
        self.horizontalLayout_9.addWidget(self.line_cargopage_total)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.bn_cargocards_page_previous = QtWidgets.QPushButton(self.frame_5)
        self.bn_cargocards_page_previous.setMinimumSize(QtCore.QSize(45, 25))
        self.bn_cargocards_page_previous.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bn_cargocards_page_previous.setFont(font)
        self.bn_cargocards_page_previous.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"    margin-top: 5px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_cargocards_page_previous.setObjectName("bn_cargocards_page_previous")
        self.horizontalLayout_9.addWidget(self.bn_cargocards_page_previous)
        self.bn_cargocards_page_next = QtWidgets.QPushButton(self.frame_5)
        self.bn_cargocards_page_next.setMinimumSize(QtCore.QSize(45, 25))
        self.bn_cargocards_page_next.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bn_cargocards_page_next.setFont(font)
        self.bn_cargocards_page_next.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"    margin-top: 5px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_cargocards_page_next.setObjectName("bn_cargocards_page_next")
        self.horizontalLayout_9.addWidget(self.bn_cargocards_page_next)
        spacerItem4 = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_home_main)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_android_field_2 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_android_field_2.sizePolicy().hasHeightForWidth())
        self.frame_android_field_2.setSizePolicy(sizePolicy)
        self.frame_android_field_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_field_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_field_2.setObjectName("frame_android_field_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_android_field_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_home_line08 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line08.setFont(font)
        self.label_home_line08.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line08.setObjectName("label_home_line08")
        self.gridLayout_7.addWidget(self.label_home_line08, 7, 0, 1, 1)
        self.line_home_value03 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value03.setEnabled(True)
        self.line_home_value03.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value03.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value03.setFont(font)
        self.line_home_value03.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value03.setText("")
        self.line_home_value03.setObjectName("line_home_value03")
        self.gridLayout_7.addWidget(self.line_home_value03, 2, 1, 1, 1)
        self.label_home_line05 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line05.setFont(font)
        self.label_home_line05.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line05.setObjectName("label_home_line05")
        self.gridLayout_7.addWidget(self.label_home_line05, 4, 0, 1, 1)
        self.label_home_line10 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line10.setFont(font)
        self.label_home_line10.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line10.setObjectName("label_home_line10")
        self.gridLayout_7.addWidget(self.label_home_line10, 9, 0, 1, 1)
        self.label_home_line02 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line02.setFont(font)
        self.label_home_line02.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line02.setObjectName("label_home_line02")
        self.gridLayout_7.addWidget(self.label_home_line02, 1, 0, 1, 1)
        self.label_home_line06 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line06.setFont(font)
        self.label_home_line06.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line06.setObjectName("label_home_line06")
        self.gridLayout_7.addWidget(self.label_home_line06, 5, 0, 1, 1)
        self.label_home_line07 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line07.setFont(font)
        self.label_home_line07.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line07.setObjectName("label_home_line07")
        self.gridLayout_7.addWidget(self.label_home_line07, 6, 0, 1, 1)
        self.line_home_value09 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value09.setEnabled(True)
        self.line_home_value09.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value09.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value09.setFont(font)
        self.line_home_value09.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value09.setText("")
        self.line_home_value09.setObjectName("line_home_value09")
        self.gridLayout_7.addWidget(self.line_home_value09, 8, 1, 1, 1)
        self.label_home_line03 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line03.setFont(font)
        self.label_home_line03.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line03.setObjectName("label_home_line03")
        self.gridLayout_7.addWidget(self.label_home_line03, 2, 0, 1, 1)
        self.line_home_value02 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value02.setEnabled(True)
        self.line_home_value02.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value02.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value02.setFont(font)
        self.line_home_value02.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value02.setText("")
        self.line_home_value02.setObjectName("line_home_value02")
        self.gridLayout_7.addWidget(self.line_home_value02, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_android_field_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bn_cargocard_edit = QtWidgets.QPushButton(self.frame_6)
        self.bn_cargocard_edit.setMinimumSize(QtCore.QSize(95, 25))
        self.bn_cargocard_edit.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.bn_cargocard_edit.setFont(font)
        self.bn_cargocard_edit.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_cargocard_edit.setObjectName("bn_cargocard_edit")
        self.horizontalLayout_8.addWidget(self.bn_cargocard_edit)
        self.bn_cargocard_delete = QtWidgets.QPushButton(self.frame_6)
        self.bn_cargocard_delete.setMinimumSize(QtCore.QSize(95, 25))
        self.bn_cargocard_delete.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.bn_cargocard_delete.setFont(font)
        self.bn_cargocard_delete.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_cargocard_delete.setObjectName("bn_cargocard_delete")
        self.horizontalLayout_8.addWidget(self.bn_cargocard_delete)
        self.bn_cargocard_create = QtWidgets.QPushButton(self.frame_6)
        self.bn_cargocard_create.setEnabled(True)
        self.bn_cargocard_create.setMinimumSize(QtCore.QSize(95, 25))
        self.bn_cargocard_create.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.bn_cargocard_create.setFont(font)
        self.bn_cargocard_create.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_cargocard_create.setObjectName("bn_cargocard_create")
        self.horizontalLayout_8.addWidget(self.bn_cargocard_create)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout_7.addWidget(self.frame_6, 10, 0, 1, 2)
        self.label_home_line09 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line09.setFont(font)
        self.label_home_line09.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line09.setObjectName("label_home_line09")
        self.gridLayout_7.addWidget(self.label_home_line09, 8, 0, 1, 1)
        self.line_home_value05 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value05.setEnabled(True)
        self.line_home_value05.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value05.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value05.setFont(font)
        self.line_home_value05.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value05.setObjectName("line_home_value05")
        self.gridLayout_7.addWidget(self.line_home_value05, 4, 1, 1, 1)
        self.line_home_value06 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value06.setEnabled(True)
        self.line_home_value06.setMinimumSize(QtCore.QSize(0, 25))
        self.line_home_value06.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value06.setFont(font)
        self.line_home_value06.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value06.setText("")
        self.line_home_value06.setObjectName("line_home_value06")
        self.gridLayout_7.addWidget(self.line_home_value06, 5, 1, 1, 1)
        self.line_home_value01 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value01.setEnabled(True)
        self.line_home_value01.setMinimumSize(QtCore.QSize(0, 25))
        self.line_home_value01.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value01.setFont(font)
        self.line_home_value01.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value01.setText("")
        self.line_home_value01.setObjectName("line_home_value01")
        self.gridLayout_7.addWidget(self.line_home_value01, 0, 1, 1, 1)
        self.line_home_value04 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value04.setEnabled(True)
        self.line_home_value04.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value04.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value04.setFont(font)
        self.line_home_value04.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value04.setText("")
        self.line_home_value04.setObjectName("line_home_value04")
        self.gridLayout_7.addWidget(self.line_home_value04, 3, 1, 1, 1)
        self.line_home_value07 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value07.setEnabled(True)
        self.line_home_value07.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value07.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value07.setFont(font)
        self.line_home_value07.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value07.setText("")
        self.line_home_value07.setObjectName("line_home_value07")
        self.gridLayout_7.addWidget(self.line_home_value07, 6, 1, 1, 1)
        self.line_home_value10 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value10.setEnabled(True)
        self.line_home_value10.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value10.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value10.setFont(font)
        self.line_home_value10.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value10.setObjectName("line_home_value10")
        self.gridLayout_7.addWidget(self.line_home_value10, 9, 1, 1, 1)
        self.label_home_line04 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line04.setFont(font)
        self.label_home_line04.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line04.setObjectName("label_home_line04")
        self.gridLayout_7.addWidget(self.label_home_line04, 3, 0, 1, 1)
        self.line_home_value08 = QtWidgets.QLineEdit(self.frame_android_field_2)
        self.line_home_value08.setEnabled(True)
        self.line_home_value08.setMinimumSize(QtCore.QSize(300, 25))
        self.line_home_value08.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.line_home_value08.setFont(font)
        self.line_home_value08.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_home_value08.setText("")
        self.line_home_value08.setObjectName("line_home_value08")
        self.gridLayout_7.addWidget(self.line_home_value08, 7, 1, 1, 1)
        self.label_home_line01 = QtWidgets.QLabel(self.frame_android_field_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_home_line01.setFont(font)
        self.label_home_line01.setStyleSheet("color:rgb(255,255,255);")
        self.label_home_line01.setObjectName("label_home_line01")
        self.gridLayout_7.addWidget(self.label_home_line01, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_android_field_2, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.horizontalLayout_19.addWidget(self.frame_home_main)
        self.vert_divide = QtWidgets.QFrame(self.page_bug)
        self.vert_divide.setFrameShape(QtWidgets.QFrame.VLine)
        self.vert_divide.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vert_divide.setObjectName("vert_divide")
        self.horizontalLayout_19.addWidget(self.vert_divide)
        self.stackedWidget.addWidget(self.page_bug)
        self.horizontalLayout_14.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_low = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame_low.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_low.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_low.setStyleSheet("")
        self.frame_low.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_low.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_low.setObjectName("frame_low")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_low)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_tab = QtWidgets.QFrame(self.frame_low)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_tab.setFont(font)
        self.frame_tab.setStyleSheet("background:rgb(51,51,51);")
        self.frame_tab.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_tab.setObjectName("frame_tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_tab)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lab_tab = QtWidgets.QLabel(self.frame_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        self.lab_tab.setFont(font)
        self.lab_tab.setStyleSheet("color:rgb(255,255,255);")
        self.lab_tab.setObjectName("lab_tab")
        self.horizontalLayout_12.addWidget(self.lab_tab)
        self.horizontalLayout_11.addWidget(self.frame_tab)
        self.frame_drag = QtWidgets.QFrame(self.frame_low)
        self.frame_drag.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_drag.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_drag.setStyleSheet("background:rgb(51,51,51);")
        self.frame_drag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_drag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_drag.setObjectName("frame_drag")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_drag)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_11.addWidget(self.frame_drag)
        self.verticalLayout_2.addWidget(self.frame_low)
        self.horizontalLayout_2.addWidget(self.frame_bottom_east)
        self.verticalLayout.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_appname.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bn_min.setToolTip(_translate("MainWindow", "Minimize"))
        self.bn_max.setToolTip(_translate("MainWindow", "Maximize"))
        self.bn_close.setToolTip(_translate("MainWindow", "Close"))
        self.bn_cargolist.setToolTip(_translate("MainWindow", "Home"))
        self.bn_cargopage.setToolTip(_translate("MainWindow", "Bug"))
        self.lab_bug_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Список транспортируемых единиц</span></p></body></html>"))
        item = self.cargolist_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.cargolist_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Категория"))
        item = self.cargolist_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата отправления"))
        item = self.cargolist_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Дата прибытия"))
        item = self.cargolist_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Пункт назначения"))
        self.label_home_main_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Транспортируемая единица</span></p></body></html>"))
        self.line_cargopage_current.setText(_translate("MainWindow", "0"))
        self.label_home_main_slash.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">/</span></p></body></html>"))
        self.line_cargopage_total.setText(_translate("MainWindow", "0"))
        self.bn_cargocards_page_previous.setText(_translate("MainWindow", "<"))
        self.bn_cargocards_page_next.setText(_translate("MainWindow", ">"))
        self.label_home_line08.setText(_translate("MainWindow", "Т / С"))
        self.label_home_line05.setText(_translate("MainWindow", "Дата прибытия"))
        self.label_home_line10.setText(_translate("MainWindow", "Пункт назначения "))
        self.label_home_line02.setText(_translate("MainWindow", "Масса"))
        self.label_home_line06.setText(_translate("MainWindow", "Категория"))
        self.label_home_line07.setText(_translate("MainWindow", "Статус"))
        self.label_home_line03.setText(_translate("MainWindow", "Оценочная стоимость "))
        self.bn_cargocard_edit.setText(_translate("MainWindow", "Изменить"))
        self.bn_cargocard_delete.setText(_translate("MainWindow", "Удалить"))
        self.bn_cargocard_create.setText(_translate("MainWindow", "Добавить"))
        self.label_home_line09.setText(_translate("MainWindow", "Пункт отправления"))
        self.label_home_line04.setText(_translate("MainWindow", "Дата отправления"))
        self.label_home_line01.setText(_translate("MainWindow", "Наименование "))
        self.lab_tab.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.frame_drag.setToolTip(_translate("MainWindow", "Drag"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
